### PR TITLE
Associate diagnostics with the offending file

### PR DESCRIPTION
**Pull request by factubsio**
For each error that `tl check` returns, check if the file is either:
    * our tmp buffer (the file that generated the request)
    * any of the other files that are present at that exact path in the workspace

associate the diagnostics with that uri and call `connection.sendDiagnostics` per-uri

### CODE REVIEW

**Comment by factubsio** [comment]
I don't know how to link to https://github.com/teal-language/vscode-teal/issues/12

**Comment by pdesaulniers** [comment]
Cool, thanks! This should work fine AFAIK.

I'll try to test this myself tomorrow, then I'll merge the PR.

**Comment by pdesaulniers** [comment]
Using your branch of the plugin, I'm getting some weird issues when I try to include a tl module from a subdirectory. For instance, given the following file structure:
```
- test.tl
- inner
    - test2.tl
```
Then, I get an error if `test.tl` contains the following code:
```lua
local test2 = require("inner.test2")
```

**Comment by pdesaulniers** [comment]
Weird, I can reproduce this issue with the official package as well. I'm investigating this...

**Comment by pdesaulniers** [comment]
OK, nevermind what I said before, I didn't understand the issue.

The problem here is that we need to send an empty diagnostic array to vscode to clear the error when it is fixed. I think we just need to add the current document to `diagnosticsByPath` by default.

I can fix this myself. Thanks!

**Comment by factubsio** [comment]
🥳

Ah nice, the errors not going away had annoyed me too but didn't know what caused it!

**Comment by factubsio** [comment]
🥳

Ah nice, the errors not going away had annoyed me too but didn't know what caused it!

**Comment by pdesaulniers** [comment]
I've just pushed this change to the Marketplace (in version 0.4.2) :tada:

**Pull request merged**
